"""lo elimine dd

Revision ID: 126237e0a03e
Revises: e519a00e0815
Create Date: 2025-02-10 02:56:09.037741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126237e0a03e'
down_revision: Union[str, None] = 'e519a00e0815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calificacion_promedio_id_calif_promedio', table_name='calificacion_promedio')
    op.drop_table('calificacion_promedio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion_promedio',
    sa.Column('id_estudiante', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('promedio_70', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('nota_proyecto', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('nota_evaluacion', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('promedio_30', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('nota_trimestre', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('promedio_cualitativo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id_calif_promedio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], name='calificacion_promedio_id_estudiante_fkey')
    )
    op.create_index('ix_calificacion_promedio_id_calif_promedio', 'calificacion_promedio', ['id_calif_promedio'], unique=False)
    # ### end Alembic commands ###
