"""Eliminar tabla calificacion_trimestre

Revision ID: 175506a9d1ff
Revises: afdb20b65c2d
Create Date: 2025-02-10 02:16:42.286857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175506a9d1ff'
down_revision: Union[str, None] = 'afdb20b65c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
