"""Esta es

Revision ID: 1ef40300aa5d
Revises: 126237e0a03e
Create Date: 2025-02-10 02:57:36.371921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef40300aa5d'
down_revision: Union[str, None] = '126237e0a03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion_promedio',
    sa.Column('id_calif_promedio', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('promedio_70', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_proyecto', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_evaluacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_30', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_trimestre', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_cualitativo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_calif_promedio')
    )
    op.create_index(op.f('ix_calificacion_promedio_id_calif_promedio'), 'calificacion_promedio', ['id_calif_promedio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calificacion_promedio_id_calif_promedio'), table_name='calificacion_promedio')
    op.drop_table('calificacion_promedio')
    # ### end Alembic commands ###
