"""Verificar eliminación de calificacion_trimestre

Revision ID: 247b9bd4e6cb
Revises: e0f1c09574be
Create Date: 2025-02-10 02:02:28.705278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247b9bd4e6cb'
down_revision: Union[str, None] = 'e0f1c09574be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion_trimestre',
    sa.Column('id_CalifPromedio', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('promedio_70', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_proyecto', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_evaluacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_30', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_trimestre', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_cualitativo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_CalifPromedio')
    )
    op.create_index(op.f('ix_calificacion_trimestre_id_CalifPromedio'), 'calificacion_trimestre', ['id_CalifPromedio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calificacion_trimestre_id_CalifPromedio'), table_name='calificacion_trimestre')
    op.drop_table('calificacion_trimestre')
    # ### end Alembic commands ###
