"""Add remaining tables

Revision ID: 2c88b1d5b031
Revises: 34b5075d6254
Create Date: 2024-12-02 07:47:27.421693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c88b1d5b031'
down_revision: Union[str, None] = '34b5075d6254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_area')
    )
    op.create_index(op.f('ix_area_id_area'), 'area', ['id_area'], unique=False)
    op.create_table('grado',
    sa.Column('id_grado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_institucion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_institucion'], ['institucion.id_institucion'], ),
    sa.PrimaryKeyConstraint('id_grado')
    )
    op.create_index(op.f('ix_grado_id_grado'), 'grado', ['id_grado'], unique=False)
    op.create_table('materia',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.Column('id_grado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['area.id_area'], ),
    sa.ForeignKeyConstraint(['id_grado'], ['grado.id_grado'], ),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_index(op.f('ix_materia_id_materia'), 'materia', ['id_materia'], unique=False)
    op.create_table('paralelo',
    sa.Column('id_paralelo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_grado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_grado'], ['grado.id_grado'], ),
    sa.PrimaryKeyConstraint('id_paralelo')
    )
    op.create_index(op.f('ix_paralelo_id_paralelo'), 'paralelo', ['id_paralelo'], unique=False)
    op.create_table('estudiante',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('id_paralelo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_paralelo'], ['paralelo.id_paralelo'], ),
    sa.PrimaryKeyConstraint('id_estudiante')
    )
    op.create_index(op.f('ix_estudiante_id_estudiante'), 'estudiante', ['id_estudiante'], unique=False)
    op.create_table('trimestre',
    sa.Column('id_trimestre', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_materia'], ['materia.id_materia'], ),
    sa.PrimaryKeyConstraint('id_trimestre')
    )
    op.create_index(op.f('ix_trimestre_id_trimestre'), 'trimestre', ['id_trimestre'], unique=False)
    op.create_table('actividad',
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('id_trimestre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_trimestre'], ['trimestre.id_trimestre'], ),
    sa.PrimaryKeyConstraint('id_actividad')
    )
    op.create_index(op.f('ix_actividad_id_actividad'), 'actividad', ['id_actividad'], unique=False)
    op.create_table('calificacion_anual',
    sa.Column('id_anual', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_materia', sa.Integer(), nullable=True),
    sa.Column('promedio_trimestres_70', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_proyecto_anual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_examen_final', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_30', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_anual_cuantitativo', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_anual_cualitativo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('nota_supletorio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estado_final', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materia.id_materia'], ),
    sa.PrimaryKeyConstraint('id_anual')
    )
    op.create_index(op.f('ix_calificacion_anual_id_anual'), 'calificacion_anual', ['id_anual'], unique=False)
    op.create_table('calificacion',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_actividad', sa.Integer(), nullable=True),
    sa.Column('nota_aporte', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_proyecto', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_evaluacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_70', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_30', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_trimestre', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_cualitativo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_actividad'], ['actividad.id_actividad'], ),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_index(op.f('ix_calificacion_id_calificacion'), 'calificacion', ['id_calificacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calificacion_id_calificacion'), table_name='calificacion')
    op.drop_table('calificacion')
    op.drop_index(op.f('ix_calificacion_anual_id_anual'), table_name='calificacion_anual')
    op.drop_table('calificacion_anual')
    op.drop_index(op.f('ix_actividad_id_actividad'), table_name='actividad')
    op.drop_table('actividad')
    op.drop_index(op.f('ix_trimestre_id_trimestre'), table_name='trimestre')
    op.drop_table('trimestre')
    op.drop_index(op.f('ix_estudiante_id_estudiante'), table_name='estudiante')
    op.drop_table('estudiante')
    op.drop_index(op.f('ix_paralelo_id_paralelo'), table_name='paralelo')
    op.drop_table('paralelo')
    op.drop_index(op.f('ix_materia_id_materia'), table_name='materia')
    op.drop_table('materia')
    op.drop_index(op.f('ix_grado_id_grado'), table_name='grado')
    op.drop_table('grado')
    op.drop_index(op.f('ix_area_id_area'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
