"""Initial migration

Revision ID: 34b5075d6254
Revises: 
Create Date: 2024-12-02 07:37:29.115404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b5075d6254'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('contraseña', sa.String(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('institucion',
    sa.Column('id_institucion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('lugar', sa.String(), nullable=False),
    sa.Column('imagen_institucion', sa.LargeBinary(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_institucion')
    )
    op.create_index(op.f('ix_institucion_id_institucion'), 'institucion', ['id_institucion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institucion_id_institucion'), table_name='institucion')
    op.drop_table('institucion')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
