"""Ultimo intento

Revision ID: 376cbdde8ec6
Revises: 56bbccb1d25d
Create Date: 2025-02-10 02:53:30.671886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376cbdde8ec6'
down_revision: Union[str, None] = '56bbccb1d25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion_promedio',
    sa.Column('id_calif_trimestre', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('promedio_70', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_proyecto', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_evaluacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_30', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_trimestre', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_cualitativo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_calif_trimestre')
    )
    op.create_index(op.f('ix_calificacion_promedio_id_calif_trimestre'), 'calificacion_promedio', ['id_calif_trimestre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calificacion_promedio_id_calif_trimestre'), table_name='calificacion_promedio')
    op.drop_table('calificacion_promedio')
    # ### end Alembic commands ###
