"""1 Agregar campo primer_ingreso a Usuario

Revision ID: 3e3194513c9b
Revises: 9dd65ec68b00
Create Date: 2025-01-13 23:59:57.125592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3194513c9b'
down_revision: Union[str, None] = '9dd65ec68b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('primer_ingreso', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'primer_ingreso')
    # ### end Alembic commands ###
