"""Ultimo intento en el id_promedio

Revision ID: 4770a50b7c22
Revises: 376cbdde8ec6
Create Date: 2025-02-10 02:54:29.954952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4770a50b7c22'
down_revision: Union[str, None] = '376cbdde8ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calificacion_promedio', sa.Column('id_calif_promedio', sa.Integer(), nullable=False))
    op.drop_index('ix_calificacion_promedio_id_calif_trimestre', table_name='calificacion_promedio')
    op.create_index(op.f('ix_calificacion_promedio_id_calif_promedio'), 'calificacion_promedio', ['id_calif_promedio'], unique=False)
    op.drop_column('calificacion_promedio', 'id_calif_trimestre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calificacion_promedio', sa.Column('id_calif_trimestre', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_calificacion_promedio_id_calif_promedio'), table_name='calificacion_promedio')
    op.create_index('ix_calificacion_promedio_id_calif_trimestre', 'calificacion_promedio', ['id_calif_trimestre'], unique=False)
    op.drop_column('calificacion_promedio', 'id_calif_promedio')
    # ### end Alembic commands ###
