"""Agregar campo estado a Usuario

Revision ID: 4b2875dfb26b
Revises: ac086af960cc
Create Date: 2025-01-01 11:59:41.108390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2875dfb26b'
down_revision: Union[str, None] = 'ac086af960cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado')
    # ### end Alembic commands ###
