"""Añadir subactividad y actualizar relaciones

Revision ID: 4b8433ff7d3e
Revises: 7dd3d892e25c
Create Date: 2025-02-08 13:52:53.663949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8433ff7d3e'
down_revision: Union[str, None] = '7dd3d892e25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subactividad',
    sa.Column('id_subactividad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_actividad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_actividad'], ['actividad.id_actividad'], ),
    sa.PrimaryKeyConstraint('id_subactividad')
    )
    op.create_index(op.f('ix_subactividad_id_subactividad'), 'subactividad', ['id_subactividad'], unique=False)
    op.drop_column('actividad', 'tipo')
    op.add_column('calificacion', sa.Column('id_subactividad', sa.Integer(), nullable=True))
    op.drop_constraint('calificacion_id_actividad_fkey', 'calificacion', type_='foreignkey')
    op.create_foreign_key(None, 'calificacion', 'subactividad', ['id_subactividad'], ['id_subactividad'])
    op.drop_column('calificacion', 'id_actividad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calificacion', sa.Column('id_actividad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'calificacion', type_='foreignkey')
    op.create_foreign_key('calificacion_id_actividad_fkey', 'calificacion', 'actividad', ['id_actividad'], ['id_actividad'])
    op.drop_column('calificacion', 'id_subactividad')
    op.add_column('actividad', sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subactividad_id_subactividad'), table_name='subactividad')
    op.drop_table('subactividad')
    # ### end Alembic commands ###
