"""Ajuate Calificacion promedio

Revision ID: 520d89958ad9
Revises: 93792fbd7e37
Create Date: 2025-02-10 01:49:11.760214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520d89958ad9'
down_revision: Union[str, None] = '93792fbd7e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calificacion_trimestre', sa.Column('id_CalifPromedio', sa.Integer(), nullable=False))
    op.drop_index('ix_calificacion_trimestre_id_trimestre_calif', table_name='calificacion_trimestre')
    op.create_index(op.f('ix_calificacion_trimestre_id_CalifPromedio'), 'calificacion_trimestre', ['id_CalifPromedio'], unique=False)
    op.drop_column('calificacion_trimestre', 'id_trimestre_calif')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calificacion_trimestre', sa.Column('id_trimestre_calif', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_calificacion_trimestre_id_CalifPromedio'), table_name='calificacion_trimestre')
    op.create_index('ix_calificacion_trimestre_id_trimestre_calif', 'calificacion_trimestre', ['id_trimestre_calif'], unique=False)
    op.drop_column('calificacion_trimestre', 'id_CalifPromedio')
    # ### end Alembic commands ###
