"""Eliminar tabla calificacion_trimestre

Revision ID: 56bbccb1d25d
Revises: 4a317a45b8c2
Create Date: 2025-02-10 02:49:38.798482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bbccb1d25d'
down_revision: Union[str, None] = '4a317a45b8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calificacion_trimestre_id_calif_trimestre', table_name='calificacion_trimestre')
    op.drop_table('calificacion_trimestre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion_trimestre',
    sa.Column('id_calif_trimestre', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_estudiante', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('promedio_70', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('nota_proyecto', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('nota_evaluacion', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('promedio_30', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('nota_trimestre', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('promedio_cualitativo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], name='calificacion_trimestre_id_estudiante_fkey'),
    sa.PrimaryKeyConstraint('id_calif_trimestre', name='calificacion_trimestre_pkey')
    )
    op.create_index('ix_calificacion_trimestre_id_calif_trimestre', 'calificacion_trimestre', ['id_calif_trimestre'], unique=False)
    # ### end Alembic commands ###
