"""Quitar estado nuevamente

Revision ID: 7279d726b856
Revises: 4b2875dfb26b
Create Date: 2025-01-01 13:07:31.808208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7279d726b856'
down_revision: Union[str, None] = '4b2875dfb26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
