"""Cambio de nombre y apellido a nombre_completo

Revision ID: 7dd3d892e25c
Revises: 9d188df10019
Create Date: 2025-02-08 10:24:29.565757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd3d892e25c'
down_revision: Union[str, None] = '9d188df10019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiante', sa.Column('nombre_completo', sa.String(), nullable=False))
    op.drop_column('estudiante', 'apellido')
    op.drop_column('estudiante', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiante', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('estudiante', sa.Column('apellido', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('estudiante', 'nombre_completo')
    # ### end Alembic commands ###
