"""2 Eliminar campo completado de usuario

Revision ID: 9c47721f5eb3
Revises: fb799cacc1de
Create Date: 2025-01-14 01:19:55.082447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c47721f5eb3'
down_revision: Union[str, None] = 'fb799cacc1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'completado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('completado', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
