"""Add TokenRecuperacion table

Revision ID: 9dd65ec68b00
Revises: 7279d726b856
Create Date: 2025-01-06 22:13:07.134434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd65ec68b00'
down_revision: Union[str, None] = '7279d726b856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_recuperacion',
    sa.Column('id_token', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_token'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_token_recuperacion_id_token'), 'token_recuperacion', ['id_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_recuperacion_id_token'), table_name='token_recuperacion')
    op.drop_table('token_recuperacion')
    # ### end Alembic commands ###
