"""Cambiar columna estado a genero en usuario

Revision ID: a2d926b516fc
Revises: e6a434595676
Create Date: 2025-01-01 11:40:48.029252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d926b516fc'
down_revision: Union[str, None] = 'e6a434595676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('genero', sa.String(), nullable=True))
    op.drop_column('usuario', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'genero')
    # ### end Alembic commands ###
