"""2 Cambiar nombre del atributo

Revision ID: a992e62ef474
Revises: 3e3194513c9b
Create Date: 2025-01-14 00:17:02.355837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a992e62ef474'
down_revision: Union[str, None] = '3e3194513c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('completado', sa.Boolean(), nullable=True))
    op.drop_column('usuario', 'primer_ingreso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('primer_ingreso', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'completado')
    # ### end Alembic commands ###
