"""3 Añadir el  campo completado de usuario

Revision ID: c102c10b8da2
Revises: 9c47721f5eb3
Create Date: 2025-01-14 01:22:06.980465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c102c10b8da2'
down_revision: Union[str, None] = '9c47721f5eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('completado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'completado')
    # ### end Alembic commands ###
