"""Crear tabla calificacion_promedio parala base de datos

Revision ID: cbf4d1f2e64b
Revises: 175506a9d1ff
Create Date: 2025-02-10 02:19:17.690480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf4d1f2e64b'
down_revision: Union[str, None] = '175506a9d1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion_trimestre',
    sa.Column('id_calif_promedio', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('promedio_70', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_proyecto', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_evaluacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_30', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_trimestre', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('promedio_cualitativo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_calif_promedio')
    )
    op.create_index(op.f('ix_calificacion_trimestre_id_calif_promedio'), 'calificacion_trimestre', ['id_calif_promedio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calificacion_trimestre_id_calif_promedio'), table_name='calificacion_trimestre')
    op.drop_table('calificacion_trimestre')
    # ### end Alembic commands ###
