"""Ajuate Calificacion dsdsdsds

Revision ID: f2fd1ece0777
Revises: 4e03f9440358
Create Date: 2025-02-10 01:53:24.671878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fd1ece0777'
down_revision: Union[str, None] = '4e03f9440358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
