"""Eliminar campo completado de usuario

Revision ID: fb799cacc1de
Revises: 47a8ca322a9d
Create Date: 2025-01-14 01:13:31.633941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb799cacc1de'
down_revision: Union[str, None] = '47a8ca322a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
